name: ew_evm
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Elite Wallet
homepage: https://elitewallet.sc

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.1
  erc20: ^1.0.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  http: ^1.1.0
  hive: ^2.2.3
  collection: ^1.17.1
  shared_preferences: ^2.0.15
  ew_core:
    path: ../ew_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
