# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1
jobs:
  build:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: decode Certificates
          command: base64 -D -o ios/Certificates.p12 \<< $Certificates
      - run:
          name: make Provisioning Profiles directory
          command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision \<< $App_Store_Profile
      - run:
          name: Test fastlane
          command: cd ios; bundle init; echo "gem 'fastlane'" > Gemfile; bundle install; bundle exec fastlane release
      - restore_cache:
          name: Restore Deps
          keys:
            - deps-cache
      - run:
          name: Build Deps
          command: ./scripts/build_deps.sh ios;
      - save_cache:
          name: Cache Deps
          key: deps-cache
          paths:
            - ew_shared_external/ios/External/sources/elite_wallet_data
      - run:
          name: Build
          command: ./scripts/build_deps.sh ios; ./scripts/build.sh --packages-only ios; .flutter/bin/flutter build ios --release --no-codesign; cd ios; bundle exec fastlane release
      - store_artifacts:
          path: build/ios/iphoneos/Runner.app
      - store_artifacts:
          path: build/ios/iphoneos/Runner.ipa

workflows:
  build-ios:
    jobs:
      - build
