# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1
jobs:
  build_deps:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: mkdir ew_shared_external/ios/External/sources/elite_wallet_data; echo uhefuwhef >> ew_shared_external/ios/External/sources/elite_wallet_data/t.txt; cat ew_shared_external/ios/External/sources/elite_wallet_data/t.txt;
      - persist_to_workspace:
          root: ew_shared_external/ios/External/sources/elite_wallet_data
          paths:
            - "*"
  build:
    macos:
      xcode: 15.3.0
    steps:
      - checkout
      - attach_workspace:
          at: ew_shared_external/ios/External/sources/elite_wallet_data
      - run:
          name: Build
          command: cat ew_shared_external/ios/External/sources/elite_wallet_data/t.txt;
      - store_artifacts:
          path: build/

workflows:
  example:
    jobs:
      - build_deps
      - build:
          requires:
            - build_deps
