# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1
jobs:
  build:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: decode Certificates
          command: base64 -D -o Certificates.p12 \<< $Certificates
      - run:
          name: make Provisioning Profiles directory
          command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision \<< $App_Store_Profile
      - run:
          name: Build an artifact
          command: ./scripts/build_deps.sh ios; ./scripts/build.sh --packages-only ios; .flutter/bin/flutter build ipa --release
      - store_artifacts:
          path: ew_shared_external/ios/External/sources/elite_wallet_data/
workflows:
  example:
    jobs:
      - build
