# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1
jobs:
  build:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run: |
          # create variables
          CERTIFICATE_PATH=~/build_certificate.p12
          PP_PATH=~/build_pp.mobileprovision
          KEYCHAIN_PATH=~/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$Certificates" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$App_Store_Profile" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - run:
          name: Build an artifact
          command: ./scripts/build_deps.sh ios; ./scripts/build.sh --packages-only ios; .flutter/bin/flutter build ipa --release
      - store_artifacts:
          path: ew_shared_external/ios/External/sources/elite_wallet_data/
workflows:
  example:
    jobs:
      - build
