blank_issues_enabled: false
contact_links:
  - name: Not sure where to start?
    url: https://guides.elitewallet.sc
    about: Start by reading checking out the guides!
  - name: Need help?
    url: https://elitewallet.sc/#contact
    about: Use our live chat or send a support email!