platform :ios do

  before_all do
    setup_circle_ci
    if ENV['TEST'].to_s.empty?
      # Variable is empty
      UI.message("TEST is empty")
    else
      # Variable is not empty
      UI.message("TEST is not empty: #{ENV['TEST']}")
    end

    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
    )
  end

  lane :release do
    build_ios_app(scheme: "elitewallet")
  end
  
end
