#!/bin/sh

APP_IOS_NAME=""
APP_IOS_VERSION=""
APP_IOS_BUILD_VERSION=""
APP_IOS_BUNDLE_ID=""

MONERO_COM="monero.com"
ELITEWALLET="elitewallet"
HAVEN="haven"
WOWNERO="wownero"

TYPES=($MONERO_COM $ELITEWALLET $HAVEN $WOWNERO)
APP_IOS_TYPE=$1

MONERO_COM_NAME="Monero.com"
MONERO_COM_VERSION="1.0.9"
MONERO_COM_BUILD_NUMBER=19
MONERO_COM_BUNDLE_ID="com.elitewallet.monero"

ELITEWALLET_NAME="Elite Wallet"
ELITEWALLET_VERSION="1.0.0"
ELITEWALLET_BUILD_NUMBER=1
ELITEWALLET_BUNDLE_ID="sc.elitewallet.elitewallet"

HAVEN_NAME="Haven"
HAVEN_VERSION="1.0.0"
HAVEN_BUILD_NUMBER=3
HAVEN_BUNDLE_ID="sc.elitewallet.haven"

WOWNERO_NAME="Wownero"
WOWNERO_VERSION="1.0.0"
WOWNERO_BUILD_NUMBER=3
WOWNERO_BUNDLE_ID="sc.elitewallet.wownero"

if ! [[ " ${TYPES[*]} " =~ " ${APP_IOS_TYPE} " ]]; then
    echo "Wrong app type."
    exit 1
fi

case $APP_IOS_TYPE in
	$MONERO_COM)
		APP_IOS_NAME=$MONERO_COM_NAME
		APP_IOS_VERSION=$MONERO_COM_VERSION
		APP_IOS_BUILD_NUMBER=$MONERO_COM_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$MONERO_COM_BUNDLE_ID
		;;
	$ELITEWALLET)
		APP_IOS_NAME=$ELITEWALLET_NAME
		APP_IOS_VERSION=$ELITEWALLET_VERSION
		APP_IOS_BUILD_NUMBER=$ELITEWALLET_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$ELITEWALLET_BUNDLE_ID
		;;
	$HAVEN)
		APP_IOS_NAME=$HAVEN_NAME
		APP_IOS_VERSION=$HAVEN_VERSION
		APP_IOS_BUILD_NUMBER=$HAVEN_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$HAVEN_BUNDLE_ID
		;;
	$WOWNERO)
		APP_IOS_NAME=$WOWNERO_NAME
		APP_IOS_VERSION=$WOWNERO_VERSION
		APP_IOS_BUILD_NUMBER=$WOWNERO_BUILD_NUMBER
		APP_IOS_BUNDLE_ID=$WOWNERO_BUNDLE_ID
		;;
esac

export APP_IOS_TYPE
export APP_IOS_NAME
export APP_IOS_VERSION
export APP_IOS_BUILD_NUMBER
export APP_IOS_BUNDLE_ID
