name: ew_ethereum
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Elite Wallet
homepage: https://elitewallet.sc

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.1
  ew_core:
    path: ../ew_core
  ew_evm:
    path: ../ew_evm
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
