#!/bin/sh

APP_MACOS_NAME=""
APP_MACOS_VERSION=""
APP_MACOS_BUILD_VERSION=""
APP_MACOS_BUNDLE_ID=""

ELITEWALLET="elitewallet"

TYPES=($ELITEWALLET)
APP_MACOS_TYPE=$ELITEWALLET

if [ -n "$1" ]; then
	APP_MACOS_TYPE=$1
fi

ELITEWALLET_NAME="Elite Wallet"
ELITEWALLET_VERSION="1.1.6"
ELITEWALLET_BUILD_NUMBER=9
ELITEWALLET_BUNDLE_ID="sc.elitewallet.elite-wallet"

if ! [[ " ${TYPES[*]} " =~ " ${APP_MACOS_TYPE} " ]]; then
    echo "Wrong app type."
    exit 1
fi

case $APP_MACOS_TYPE in
	$ELITEWALLET)
		APP_MACOS_NAME=$ELITEWALLET_NAME
		APP_MACOS_VERSION=$ELITEWALLET_VERSION
		APP_MACOS_BUILD_NUMBER=$ELITEWALLET_BUILD_NUMBER
		APP_MACOS_BUNDLE_ID=$ELITEWALLET_BUNDLE_ID;;
esac

export APP_MACOS_TYPE
export APP_MACOS_NAME
export APP_MACOS_VERSION
export APP_MACOS_BUILD_NUMBER
export APP_MACOS_BUNDLE_ID
