name: Cache Dependencies

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Execute Build and Setup Commands
        run: |
          sudo mkdir -p /opt/android
          sudo chown $USER /opt/android
          cd /opt/android
          git clone https://github.com/Elite-Labs/EliteWallet --branch main
          cd EliteWallet/
          ./scripts/build_deps.sh --skip_main_deps android

      - name: Cache Externals
        id: cache-externals
        uses: actions/cache@v3
        with:
          path: |
            /opt/android/EliteWallet/ew_haven/android/.cxx
            /opt/android/EliteWallet/ew_haven/ios/External
            /opt/android/EliteWallet/ew_monero/android/.cxx
            /opt/android/EliteWallet/ew_monero/ios/External
            /opt/android/EliteWallet/ew_wownero/android/.cxx
            /opt/android/EliteWallet/ew_wownero/ios/External
            /opt/android/EliteWallet/ew_shared_external/ios/External
          key: ${{ hashFiles('**/build_monero.sh', '**/build_haven.sh', '**/build_wownero.sh', '**/monero_api.cpp', '**/haven_api.cpp', '**/wownero_api.cpp') }}

      - if: ${{ steps.cache-externals.outputs.cache-hit != 'true' }}
        name: Generate Externals
        run: |
          cd /opt/android/EliteWallet/
          ./scripts/build_deps.sh android
